[app]
name = "workflow"
key = "workflow_key"

[http]
host = "127.0.0.1"
port = "8848"
enable_ssl = false 
cert_file = ""
key_file = "" 

[grpc]
host = "127.0.0.1"
port = "18848"
enable_ssl = false 
cert_file = ""
key_file = "" 

[mongodb]
endpoints = ["127.0.0.1:27017"]
username = "workflow"
password = "workflow"
database = "workflow"

[etcd]
endpoints = ["127.0.0.1:2379"]
username = "workflow"
password = "workflow"
prefix = "inforboard"
instance_ttl = 300


[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"

[keyauth]
host = "10.40.44.101"
port = "8050"
client_id = "" 
client_secret = ""

[cache]

[nats]

[bus]
type = "nats"

